set -g tide_git_color_branch blue
set -g tide_git_color_untracked green
set -g tide_git_color_staged yellow
set -g tide_git_color_dirty blue
set -g tide_git_color_conflicted red
set -g tide_git_color_upstream red
set -g tide_git_color_stash white
set -g tide_git_color_operation red
set -g tide_git_icon ''
