require('skkeleton_indicator').setup({
  eijiHlName = 'SkkeletonIndicatorEiji',
  hiraHlName = 'SkkeletonIndicatorHira',
  kataHlName = 'SkkeletonIndicatorKata',
  hankataHlName = 'SkkeletonIndicatorHankata',
  zenkakuHlName = 'SkkeletonIndicatorZenkaku',
  abbrevHlName = 'SkkeletonIndicatorAbbrev',
  eijiText = 'A',
  hiraText = 'あ',
  kataText = 'ア',
  hankataText = 'ｶﾅ',
  zenkakuText = 'ＡＺ',
  abbrevText = 'abbr',
  -- border = 'rounded',
  row = 0,
  col = 1,
  zindex = nil,
  alwaysShown = false,
  fadeOutMs = 3000,
  ignoreFt = {},
})
