return {
  'Eutrius/Otree.nvim',
  lazy = false,
  dependencies = {
    'nvim-tree/nvim-web-devicons',
    'stevearc/oil.nvim',
  },
  config = function()
    require('Otree').setup({
      win_size = 40,
      open_on_startup = false,
      use_default_keymaps = true,
      hijack_netrw = false,
      show_hidden = false,
      show_ignore = false,
      cursorline = true,
      ignore_patterns = {},
      keymaps = {
        ['<CR>'] = 'actions.on_enter',
        ['l'] = 'actions.on_enter',
        ['h'] = 'actions.on_close_dir',
        ['q'] = 'actions.close_win',
        ['<C-h>'] = 'actions.goto_parent',
        ['<C-l>'] = 'actions.goto_dir',
        ['<M-h>'] = 'actions.goto_pwd',
        ['cd'] = 'actions.change_pwd',
        ['L'] = 'actions.open_dirs',
        ['H'] = 'actions.close_dirs',
        ['o'] = 'actions.edit_dir',
        ['O'] = 'actions.edit_into_dir',
        ['t'] = 'actions.open_tab',
        ['v'] = 'actions.open_vsplit',
        ['s'] = 'actions.open_split',
        ['r'] = 'actions.refresh',
        ['f'] = 'actions.focus_file',
        ['.'] = 'actions.toggle_hidden',
        ['i'] = 'actions.toggle_ignore',
      },
    })
  end,
}

-- return {
--   'Eutrius/Otree.nvim',
--   lazy = false,
--   dependencies = {
--     'nvim-tree/nvim-web-devicons',
--     'stevearc/oil.nvim',
--   },
--   opts = {
--     win_size = 40,
--     open_on_startup = false,
--     use_default_keymaps = true,
--     hijack_netrw = false,
--     show_hidden = false,
--     show_ignore = false,
--     cursorline = true,
--     ignore_patterns = {},
--     keymaps = {
--       ['<CR>'] = 'actions.on_enter',
--       ['l'] = 'actions.on_enter',
--       ['h'] = 'actions.on_close_dir',
--       ['q'] = 'actions.close_win',
--       ['<C-h>'] = 'actions.goto_parent',
--       ['<C-l>'] = 'actions.goto_dir',
--       ['<M-h>'] = 'actions.goto_pwd',
--       ['cd'] = 'actions.change_pwd',
--       ['L'] = 'actions.open_dirs',
--       ['H'] = 'actions.close_dirs',
--       ['o'] = 'actions.edit_dir',
--       ['O'] = 'actions.edit_into_dir',
--       ['t'] = 'actions.open_tab',
--       ['v'] = 'actions.open_vsplit',
--       ['s'] = 'actions.open_split',
--       ['r'] = 'actions.refresh',
--       ['f'] = 'actions.focus_file',
--       ['.'] = 'actions.toggle_hidden',
--       ['i'] = 'actions.toggle_ignore',
--     },
--   },
-- }
