-- require('hlslens').setup()
-- vim.keymap.set('n', '*', function()
--   require('lasterisk').search()
--   require('hlslens').start()
-- end)
--
-- vim.keymap.set({ 'n', 'x' }, 'g*', function()
--   require('lasterisk').search({ is_whole = false })
--   require('hlslens').start()
-- end)
-- --local kopts = { noremap = true, silent = true }
--
-- -- vim.api.nvim_set_keymap(
-- --   'n',
-- --   'n',
-- --   [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
-- --   kopts
-- -- )
-- -- vim.api.nvim_set_keymap(
-- --   'n',
-- --   'N',
-- --   [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
-- --   kopts
-- -- )
-- -- vim.api.nvim_set_keymap('n', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
-- -- vim.api.nvim_set_keymap('n', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
-- -- vim.api.nvim_set_keymap('n', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
-- -- vim.api.nvim_set_keymap('n', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)
