vim.keymap.set('n', 'gTM', ":lua require('java').test.run_current_method()<CR>", { silent = true })
vim.keymap.set('n', 'gTC', ":lua require('java').test.run_current_class()<CR>", { silent = true })
vim.keymap.set('n', 'gTV', function()
  vim.cmd([[ vsplit ]])
  require('java').test.view_last_report()
end, { silent = true })
