version: 2
root-markers:
  - .git/

tools:
  markdown-textlint: &markdown-textlint
    lint-command: "textlint --format unix --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m [%trror/%r]"
    root-markers:
      - .textlintrc

  vim-vint: &vim-vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  markdown:
    - <<: *markdown-textlint
  vim:
    - <<: *vim-vint
