[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-istaller'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'vim-skk/skkeleton'
